apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: neurafleet
  labels:
    app: gateway
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: neurafleet
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: neurafleet
  labels:
    app: gateway
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: neurafleet
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "neurafleet-ip"
    networking.gke.io/managed-certificates: "neurafleet-cert"
spec:
  defaultBackend:
    service:
      name: gateway
      port:
        number: 8000
  rules:
    - host: api.neurafleet.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8000
