apiVersion: v1
kind: Service
metadata:
  name: lidar-service
  namespace: neurafleet
  labels:
    app: lidar-service
    app.kubernetes.io/name: lidar-service
    app.kubernetes.io/part-of: neurafleet
spec:
  type: ClusterIP
  selector:
    app: lidar-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
